# Generated by Django 3.0.5 on 2021-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='empid',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
