# Generated by Django 3.0.5 on 2021-05-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210515_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='commission',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
