# Generated by Django 3.0.5 on 2021-05-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210515_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='commission',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emp',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
